"use client"

import Head from "next/head";
import Image from "next/image";
import headerStyles from "@/styles/ryohi/header.module.scss";
import fvStyles from "@/styles/ryohi/fv.module.scss";
import serviceStyles from "@/styles/ryohi/service.module.scss";
import explanationStyles from "@/styles/ryohi/explanation.module.scss";
import reviewsStyles from "@/styles/ryohi/reviews.module.scss";
import productStyles from "@/styles/ryohi/product.module.scss";
import footerStyles from "@/styles/ryohi/footer.module.scss";
import { useEffect } from "react";




export default function Home() {

    useEffect(() => {
        const burger = document.getElementById("burger");
        const burgerNav = document.getElementById("burgerNav");
        const lists = document.getElementsByClassName(explanationStyles.lists);
        
        if (burger && burgerNav) {
            burger.addEventListener("click", () => {
                burger.classList.toggle(headerStyles.isActive);
                burgerNav.classList.toggle(headerStyles.isActive);
            });
        }

        // 各リスト項目に対してクリックイベントを追加
        Array.from(lists).forEach((list) => {
            list.addEventListener("click", handleClick);
        });

        // クリーンアップ処理でリスナーを削除
        return () => {
            Array.from(lists).forEach((list) => {
                list.removeEventListener("click", handleClick);
            });
        };
    }, []);

    // クリック時の処理
    const handleClick = (event: Event) => {
        const target = event.currentTarget as HTMLElement;

        // 全てのリストから isActive クラスを削除
        const lists = document.getElementsByClassName(explanationStyles.lists);
        Array.from(lists).forEach((list) => {
            list.classList.remove(explanationStyles.isActive);
        });

        // クリックされたリストに isActive クラスを追加
        target.classList.add(explanationStyles.isActive);

    };

    return (
        <>
            <Head>
                <title>ryohi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic&family=Zen+Old+Mincho&display=swap" rel="stylesheet" />
            </Head>
            <header className={headerStyles.header}>
                <div className={headerStyles.right}>
                    株式会社 AZ
                </div>
                <nav className={headerStyles.left}>
                    <a href="" className={headerStyles.link}>
                        ホーム
                    </a>
                    <a href="" className={headerStyles.link}>
                        サービス
                    </a>
                    <a href="" className={headerStyles.link}>
                        旅費規定とは
                    </a>
                    <a href="" className={headerStyles.link}>
                        お客様の声
                    </a>
                    <a href="" className={headerStyles.link}>
                        商品
                    </a>

                    <div className={headerStyles.burgerBox} id="burger">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>

                </nav>
                <nav className={headerStyles.burgerNav} id="burgerNav">
                    <ul className={headerStyles.navList}>
                        <li className={headerStyles.list}>
                            <a href="" className={headerStyles.link}>
                                ホーム
                            </a>
                        </li>
                        <li className={headerStyles.list}>
                            <a href="" className={headerStyles.link}>
                                サービス
                            </a>
                        </li>
                        <li className={headerStyles.list}>
                            <a href="" className={headerStyles.link}>
                                説明
                            </a>
                        </li>
                        <li className={headerStyles.list}>
                            <a href="" className={headerStyles.link}>
                                お客様の声
                            </a>
                        </li>
                        <li className={headerStyles.list}>
                            <a href="" className={headerStyles.link}>
                                商品
                            </a>
                        </li>
                    </ul>
                    <Image src="/ryohi/image 3.png" alt="" className={headerStyles.tree} width={155} height={155} />
                </nav>
            </header>

            <section className={fvStyles.fv}>
                <Image src="/ryohi/Group 37.png" alt="" className={fvStyles.bgImg} width={1300} height={800} />
                <div className={fvStyles.left}>
                    <h1 className={fvStyles.catchcopy}>
                        キャッチコピー
                    </h1>
                    <p className={fvStyles.text}>
                        テキストテキストテキストテキストテキストテキスト
                        テキストテキストテキストテキストテキストテキスト
                    </p>
                </div>

                <div className={fvStyles.right}>

                    <div className={fvStyles.mark}>
                        簡単にわかる資料を5分で!
                    </div>
                    <div className={fvStyles.triangle}></div>
                    <a href="" className={fvStyles.link}>
                        資料請求
                    </a>
                </div>
            </section>

            <section className={serviceStyles.service}>
                <div className={serviceStyles.titleBox}>
                    <h2 className={serviceStyles.title}>
                        サービス
                    </h2>
                </div>
                <div className={serviceStyles.boxs}>
                    <ul className={serviceStyles.listBox}>
                        <li className={serviceStyles.list}>
                            <h3 className={serviceStyles.listTitle}>
                                たいとる
                            </h3>
                            <Image src="/ryohi/Rectangle 8.png" alt="" className={serviceStyles.img} width={360} height={200} />
                            <p className={serviceStyles.text}>
                                テキストテキストテキストテキストテキストテキスト
                                テキストテキストテキストテキストテキストテキスト
                            </p>
                        </li>
                        <li className={serviceStyles.list}>
                            <h3 className={serviceStyles.listTitle}>
                                たいとる
                            </h3>
                            <Image src="/ryohi/Rectangle 10.png" alt="" className={serviceStyles.img} width={360} height={200} />
                            <p className={serviceStyles.text}>
                                テキストテキストテキストテキストテキストテキスト
                                テキストテキストテキストテキストテキストテキスト
                            </p>
                        </li>
                        <li className={serviceStyles.list}>
                            <h3 className={serviceStyles.listTitle}>
                                たいとる
                            </h3>
                            <Image src="/ryohi/Rectangle 10-1.png" alt="" className={serviceStyles.img} width={360} height={200} />
                            <p className={serviceStyles.text}>
                                テキストテキストテキストテキストテキストテキスト
                                テキストテキストテキストテキストテキストテキスト
                            </p>
                        </li>
                    </ul>
                </div>
            </section>



            <section className={explanationStyles.explanation}>
                <div className={explanationStyles.titleBox}>
                    <h2 className={explanationStyles.title}>
                        旅費規定の説明
                    </h2>
                </div>
                <div className={explanationStyles.main}>

                    <ul className={explanationStyles.listBox}>
                        <li className={explanationStyles.lists}>
                            <div className={explanationStyles.top}>
                                <div className={explanationStyles.left}>
                                    1.旅費規定とは
                                </div>
                                <div className={explanationStyles.right}>
                                    <Image src="/ryohi/Vector.png" alt="" className={explanationStyles.arrow} width={25} height={15} />
                                </div>
                            </div>

                            <div className={explanationStyles.bottom}>
                                <div className={explanationStyles.text}>
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                </div>
                                <Image src="/ryohi/出張-removebg-preview 2.png" alt="" className={explanationStyles.img} width={330} height={275} />
                            </div>
                        </li>

                        <li className={explanationStyles.lists}>
                            <div className={explanationStyles.top}>
                                <div className={explanationStyles.left}>
                                    1.旅費規定とは
                                </div>
                                <div className={explanationStyles.right}>
                                    <Image src="/ryohi/Vector.png" alt="" className={explanationStyles.arrow} width={25} height={15} />
                                </div>
                            </div>

                            <div className={explanationStyles.bottom}>
                                <div className={explanationStyles.text}>
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                </div>
                                <Image src="/ryohi/出張-removebg-preview 2.png" alt="" className={explanationStyles.img} width={330} height={275} />
                            </div>
                        </li>

                        <li className={explanationStyles.lists}>
                            <div className={explanationStyles.top}>
                                <div className={explanationStyles.left}>
                                    1.旅費規定とは
                                </div>
                                <div className={explanationStyles.right}>
                                    <Image src="/ryohi/Vector.png" alt="" className={explanationStyles.arrow} width={25} height={15} />
                                </div>
                            </div>

                            <div className={explanationStyles.bottom}>
                                <div className={explanationStyles.text}>
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト
                                </div>
                                <Image src="/ryohi/出張-removebg-preview 2.png" alt="" className={explanationStyles.img} width={330} height={275} />
                            </div>
                        </li>
                    </ul>
                </div>
            </section>



            <section className={reviewsStyles.reviews}>
                <div className={reviewsStyles.titleBox}>
                    <h2 className={reviewsStyles.title}>
                        お客様の声
                    </h2>
                </div>

                <div className={reviewsStyles.main}>
                    <ul className={reviewsStyles.listBox}>
                        <li className={reviewsStyles.list}>

                            <div className={reviewsStyles.left}>

                                <div className={reviewsStyles.company}>
                                    ABCD株式会社
                                </div>
                                <div className={reviewsStyles.position}>
                                    代表取締役
                                </div>
                                <div className={reviewsStyles.name}>
                                    山田 友策
                                </div>
                            </div>

                            <div className={reviewsStyles.right}>
                                <p className={reviewsStyles.text}>
                                    テキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキスト
                                </p>
                            </div>
                            <Image src="/ryohi/Rectangle 20.png" alt="" className={reviewsStyles.img} width={170} height={170} />
                            <div className={reviewsStyles.bgColor}></div>
                        </li>
                        <li className={reviewsStyles.list}>

                            <div className={reviewsStyles.left}>

                                <div className={reviewsStyles.company}>
                                    ABCD株式会社
                                </div>
                                <div className={reviewsStyles.position}>
                                    代表取締役
                                </div>
                                <div className={reviewsStyles.name}>
                                    山田 友策
                                </div>
                            </div>

                            <div className={reviewsStyles.right}>
                                <p className={reviewsStyles.text}>
                                    テキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキスト
                                </p>
                            </div>
                            <Image src="/ryohi/Rectangle 20.png" alt="" className={reviewsStyles.img} width={170} height={170} />
                            <div className={reviewsStyles.bgColor}></div>
                        </li>
                        <li className={`${reviewsStyles.list} ${reviewsStyles.displayNone}`}>

                            <div className={reviewsStyles.left}>

                                <div className={reviewsStyles.company}>
                                    ABCD株式会社
                                </div>
                                <div className={reviewsStyles.position}>
                                    代表取締役
                                </div>
                                <div className={reviewsStyles.name}>
                                    山田 友策
                                </div>
                            </div>

                            <div className={reviewsStyles.right}>
                                <p className={reviewsStyles.text}>
                                    テキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキスト
                                </p>
                            </div>
                            <Image src="/ryohi/Rectangle 20.png" alt="" className={reviewsStyles.img} width={170} height={170} />
                            <div className={reviewsStyles.bgColor}></div>
                        </li>
                        <li className={`${reviewsStyles.list} ${reviewsStyles.displayNone}`}>

                            <div className={reviewsStyles.left}>

                                <div className={reviewsStyles.company}>
                                    ABCD株式会社
                                </div>
                                <div className={reviewsStyles.position}>
                                    代表取締役
                                </div>
                                <div className={reviewsStyles.name}>
                                    山田 友策
                                </div>
                            </div>

                            <div className={reviewsStyles.right}>
                                <p className={reviewsStyles.text}>
                                    テキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキスト
                                    テキストテキストテキストテキストテキストテキスト
                                </p>
                            </div>
                            <Image src="/ryohi/Rectangle 20.png" alt="" className={reviewsStyles.img} width={170} height={170} />
                            <div className={reviewsStyles.bgColor}></div>
                        </li>
                    </ul>
                </div>
            </section>

            <section className={productStyles.product}>
                <div className={productStyles.titleBox}>
                    <h2 className={productStyles.title}>
                        我が社の商品
                    </h2>
                </div>

                <div className={productStyles.main}>
                    <div className={productStyles.mainTitleBox}>
                        <h3 className={productStyles.title}>
                            しょうひんめい
                        </h3>
                    </div>
                    <div className={productStyles.bottom}>
                        <Image src="/ryohi/4074467_s 1.png" alt="" className={productStyles.book} width={600} height={500} />
                        <Image src="/ryohi/名称_未_設定 (4) 2.png" alt="" className={productStyles.point} width={200} height={140} />
                        <div className={productStyles.textBox}>
                            <h3 className={productStyles.title}>
                                プロが監修した簡単設計
                            </h3>
                            <p className={productStyles.text}>
                                テキストテキストテキストテキストテキストテキスト
                                テキストテキストテキストテキストテキストテキスト
                                テキストテキストテキストテキストテキストテキスト
                            </p>
                        </div>
                        <div className={productStyles.buycard}>
                            <h3 className={productStyles.title}>
                                とてもお得なオープン価格
                            </h3>
                            <p className={productStyles.text}>
                                この価格は今だけの超お得な価格 <br />
                                興味のある方はぜひ!
                            </p>
                            <div className={productStyles.moneyBox}>
                                <p className={productStyles.cheap}>
                                    現在価格 : 60000円
                                </p>
                                <p className={productStyles.expensive}>
                                    セール価格 : 100000円
                                </p>
                            </div>
                            <div className={productStyles.btnBox}>
                                <a href="" className={productStyles.buyBtn}>
                                    購入はこちら
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <footer className={footerStyles.footer}>
                <p className={footerStyles.text}>
                    © 2024 株式会社 AZ
                </p>
                <p className={footerStyles.text}>
                    東京都0丁目 0-0
                </p>
                <p className={footerStyles.text}>
                    営業時間 : 0~24時
                </p>
                <div className={footerStyles.account}>
                    <a href="" className={footerStyles.url}>
                        Twitter
                    </a>
                    <a href="" className={footerStyles.url}>
                        Facebook
                    </a>
                    <a href="" className={footerStyles.url}>
                        Instagram
                    </a>
                </div>
            </footer>
        </>
    )
}