import Head from "next/head";
import Image from "next/image";
import headerStyles from "@/styles/portfolio/header.module.scss";
import footerStyles from "@/styles/portfolio/footer.module.scss";
import contactStyles from "@/styles/portfolio/contact/contact.module.scss";

export default function Home() {
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New&family=Zen+Maru+Gothic&display=swap" rel="stylesheet" />
            </Head>
            <header className={headerStyles.header}>

                <div className={headerStyles.left}>
                    DAIKI
                </div>
                <ul className={headerStyles.right}>
                    <li className={headerStyles.list}>
                        <a href="" className={headerStyles.link}>
                            Home
                        </a>
                    </li>
                    <li className={headerStyles.list}>
                        <a href="" className={headerStyles.link}>
                            About
                        </a>
                    </li>
                    <li className={headerStyles.list}>
                        <a href="" className={headerStyles.link}>
                            Contact
                        </a>
                    </li>
                </ul>

                <div className={headerStyles.burgerBox}>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>

            </header>
            <main style={{ backgroundColor: 'var(--portfolioMainBg)' }}>


                <section className={contactStyles.contact}>
                    <div className={contactStyles.titleBox}>
                        <h1 className={contactStyles.title}>
                            Contact
                        </h1>
                    </div>

                    <div className={contactStyles.main}>
                        <div className={contactStyles.inputBox}>
                            <p className={contactStyles.text}>
                                お名前<span>*</span>
                            </p>
                            <input type="text" className={contactStyles.input} placeholder="例 : 後藤 大輝" />
                        </div>
                        <div className={contactStyles.inputBox}>
                            <p className={contactStyles.text}>
                                メールアドレス<span>*</span>
                            </p>
                            <input type="email" className={contactStyles.input} placeholder="例 : info@example.com" />
                        </div>
                        <div className={contactStyles.inputBox}>
                            <p className={contactStyles.text}>
                                メッセージ<span>*</span>
                            </p>
                            <textarea className={contactStyles.textarea} placeholder="メッセージを入力" />
                        </div>
                    </div>
                    <div className={contactStyles.btnBox}>
                    <button className={contactStyles.btn}>
                        送信
                    </button>
                    </div>
                </section>


            <footer className={footerStyles.footer}>
                    <ul className={footerStyles.listBox}>
                        <li className={footerStyles.list}>
                            <a href="" className={footerStyles.link}>
                                <div className={footerStyles.lineLeft}></div>
                                <p className={footerStyles.text}>
                                    Home
                                </p>
                                <div className={footerStyles.lineRight}></div>
                            </a>
                        </li>
                        <li className={`${footerStyles.list} ${footerStyles.displayNone}`}>
                            <a href="/About/" className={footerStyles.link}>
                                <div className={footerStyles.lineLeft}></div>
                                <p className={footerStyles.text}>
                                    About
                                </p>
                                <div className={footerStyles.lineRight}></div>
                            </a>
                        </li>
                        <li className={footerStyles.list}>
                            <a href="/contact/" className={footerStyles.link}>
                                <div className={footerStyles.lineLeft}></div>
                                <p className={footerStyles.text}>
                                    Contact
                                </p>
                                <div className={footerStyles.lineRight}></div>
                            </a>
                        </li>
                    </ul>
                </footer>
            </main>
        </>
    );
}
