import Head from "next/head";
import Image from "next/image";
import headerStyles from "@/styles/portfolio/header.module.scss";
import fvStyles from "@/styles/portfolio/fv.module.scss";
import worksStyles from "@/styles/portfolio/works.module.scss";
import footerStyles from "@/styles/portfolio/footer.module.scss";
import { useEffect } from "react";


export default function Home() {
  useEffect(() => {
    const burger = document.getElementById("burger");
    const burgerNav = document.getElementById("burgerNav");

    if (burger && burgerNav) {
      burger.addEventListener("click", () => {
        burger.classList.toggle(headerStyles.isActive);
        burgerNav.classList.toggle(headerStyles.isActive);
      });
    }
  })
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Zen+Kaku+Gothic+New&family=Zen+Maru+Gothic&display=swap" rel="stylesheet" />
      </Head>
      <header className={headerStyles.header}>

        <div className={headerStyles.left}>
          DAIKI
        </div>
        <ul className={headerStyles.right}>
          <li className={headerStyles.list}>
            <a href="" className={headerStyles.link}>
              Home
            </a>
          </li>
          <li className={headerStyles.list}>
            <a href="" className={headerStyles.link}>
              About
            </a>
          </li>
          <li className={headerStyles.list}>
            <a href="" className={headerStyles.link}>
              Contact
            </a>
          </li>
        </ul>

        <div className={headerStyles.burgerBox} id="burger">
          <span></span>
          <span></span>
          <span></span>
        </div>

        <nav className={headerStyles.burgerNav} id="burgerNav">
          <ul className={headerStyles.navList}>
            <li className={headerStyles.list}>
              <a href="" className={headerStyles.link}>
                Home
              </a>
            </li>
            <li className={headerStyles.list}>
              <a href="" className={headerStyles.link}>
                About
              </a>
            </li>
            <li className={headerStyles.list}>
              <a href="" className={headerStyles.link}>
                Contact
              </a>
            </li>
          </ul>
        </nav>

      </header>
      <main style={{ backgroundColor: 'var(--portfolioMainBg)' }}>
        <section className={fvStyles.fv}>
          <div className={fvStyles.top}>
            <div className={fvStyles.imgBox}>
              <Image src="/portfolio/titlePc.png" alt="" className={fvStyles.titlePc} width={848} height={223} />
            </div>
            <div className={fvStyles.text}>
              Daikis Portfolio
            </div>
          </div>

          <div className={fvStyles.under}>
            <h1 className={fvStyles.title}>
              僕がデザイナーになる理由
            </h1>
            <p className={fvStyles.text}>
              自由なデザインで、デザインの枠をはみでるデザイン
            </p>
            <p className={fvStyles.text}>
              パッとみただけで想いを伝えられるデザイン
            </p>
            <p className={fvStyles.text}>
              自由で想いを伝えられるデザインをしたいから
            </p>
            <Image className={fvStyles.left} src="/portfolio/reasonLeft.png" alt="" width={123} height={103} />
            <Image className={fvStyles.right} src="/portfolio/reasonRight.png" alt="" width={165} height={169} />
          </div>
        </section>

        <section className={worksStyles.works}>
          <div className={worksStyles.titleBox}>
            <h1 className={worksStyles.title}>
              Works
            </h1>
          </div>
          <ul className={worksStyles.listBox}>
            <li className={worksStyles.list}>
              <div className={worksStyles.left}>
                <Image src="" alt="" className={worksStyles.leftImg} width={500} height={300} />
              </div>
              <div className={worksStyles.right}>
                <h3 className={worksStyles.listTitle}>
                  このポートフォリオ
                </h3>
                <p className={worksStyles.text}>
                  テキストテキストテキストテキストテキストテキスト
                  テキストテキストテキストテキストテキスト
                </p>
              </div>
            </li>
            <li className={worksStyles.list}>
              <div className={worksStyles.left}>
                <Image src="" alt="" className={worksStyles.leftImg} width={500} height={300} />
              </div>
              <div className={worksStyles.right}>
                <h3 className={worksStyles.listTitle}>
                  このポートフォリオ
                </h3>
                <p className={worksStyles.text}>
                  テキストテキストテキストテキストテキストテキスト
                  テキストテキストテキストテキストテキスト
                </p>
              </div>
            </li>
            <li className={worksStyles.list}>
              <div className={worksStyles.left}>
                <Image src="" alt="" className={worksStyles.leftImg} width={500} height={300} />
              </div>
              <div className={worksStyles.right}>
                <h3 className={worksStyles.listTitle}>
                  このポートフォリオ
                </h3>
                <p className={worksStyles.text}>
                  テキストテキストテキストテキストテキストテキスト
                  テキストテキストテキストテキストテキスト
                </p>
              </div>
            </li>
            <li className={worksStyles.list}>
              <div className={worksStyles.left}>
                <Image src="" alt="" className={worksStyles.leftImg} width={500} height={300} />
              </div>
              <div className={worksStyles.right}>
                <h3 className={worksStyles.listTitle}>
                  このポートフォリオ
                </h3>
                <p className={worksStyles.text}>
                  テキストテキストテキストテキストテキストテキスト
                  テキストテキストテキストテキストテキスト
                </p>
              </div>
            </li>
          </ul>
        </section>

        <footer className={footerStyles.footer}>
          <ul className={footerStyles.listBox}>
            <li className={`${footerStyles.list} ${footerStyles.displayNone}`}>
              <a href="" className={footerStyles.link}>
                <div className={footerStyles.lineLeft}></div>
                <p className={footerStyles.text}>
                  Home
                </p>
                <div className={footerStyles.lineRight}></div>
              </a>
            </li>
            <li className={footerStyles.list}>
              <a href="" className={footerStyles.link}>
                <div className={footerStyles.lineLeft}></div>
                <p className={footerStyles.text}>
                  About
                </p>
                <div className={footerStyles.lineRight}></div>
              </a>
            </li>
            <li className={footerStyles.list}>
              <a href="" className={footerStyles.link}>
                <div className={footerStyles.lineLeft}></div>
                <p className={footerStyles.text}>
                  Contact
                </p>
                <div className={footerStyles.lineRight}></div>
              </a>
            </li>
          </ul>
        </footer>
      </main>
    </>
  );
}
